# endpoint: https://countries.trevorblades.com

{
  countries {
    code
    name
  }
}

# variables: {
#   "code": "US"
# }
query Country($code: ID!) {
  country(code: $code) {
    code
    name
  }
}
